apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:7WSKUl9bGoJvAU9nSwLDiOiFJhkEzcppFQz6oZ7HnsKY1wSugZHEW7OaJWZOXVNj6DqKYDVunocokn8v0yuE0T/EfTEYU4gelcAtYNCkFJ7XS3gJ07jqIVdcrjLoAJ7RiPhtwAFLVOUxyncZ7H1ij8JMXuDCN9nF8xZxt1S0zzERWyqgm2lIaoNv1L60kNBRf4l0bU8gaQ+9VN53Y7loxehTp522KMmgzvs2nToIVf9ZE9NkAY9rXwGIA4FxBFwE6Or6/AzNBUVI9m88IEmtpJWqECWgcwLhbexb//audHE5qCy+ty2i4fyiNn8=,iv:zz/FirDX1WBv+6uxaElA54BLnOBB47KFKx++wFf/700=,tag:WAnf415xz88RVOUFQHmoSg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cXg1dVVXWk9UMXZ2RTRw
            bzFPZ21vc2JvbVdLaXEyaURQblN2T2dLeEdRCks1MGwrNmFoWk4xZXhyMFRnNW9r
            QXFVeHlzeHpaaW5IV0JKUUZsYU96b0UKLS0tIGdxWlk5SlVQVnkvVzNoUjJCSVhF
            VkdEU3VZM3lRVzZxM2c1UVpIWUh5NWsKbKAgavxUqO0fctwplBsssVqMvR/4+9ld
            b1x48v1BrKfxdCAzLVsBbSe1gtZGViT6/uwVEUq7peNB6FUYj2vjNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwm4xvd23tsx8m0h6xgxghkcxjzhucwm2djdfg0m88fwysjvdeys8gwn5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T19:20:37Z"
    mac: ENC[AES256_GCM,data:xPpejhWu/UKFPGHln7g8R9NbUSeWAz6lT+XtB2BlRSB+/4bPQWq8CrD3QlZV8JCdpH+IKBBnh/G18Wn/2xOSe9/mGWbcW7vqzrP4xAbQSVc1pqPhYE4ofFKKDLCztwu5ulqBWxPSR9JcF0sZl7iHvXtL4UvcsRK1rBAPa2Wp4IU=,iv:WQ3bQQwE5OjHs/f7P8KB5xjPH3uzKzIPX2vVBINCN+c=,tag:dZn+k1IUIrgODbEBaEvtHg==,type:str]
    version: 3.13.3
