apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:OU9i9b03LIzbaHT5SnfxQj5cHq+0sdbY7QpV9DJLUnDDD/9xGu9ACgkT5TRMSWY99kDUQkxoHnMcNCoowBcki+r4+y/otN6NflIuIrGRfS80EKrI+I1L/ICpEm24k1gOiruZ6uDvsLiJ1SRZ68D4oPwzfvgVv8EWx5WMU2ck6ddJAUWGPpFvl3JfCz1aLAGJlBINzFWDgW4h45fTmXCNPAai9DfzDMHjYSU7KhY+yXmGIP2ZMT2HqByP75A2Do3UvqDZhrBd5LjkrOvFtkKMv/T4lplQHj+whPfQV9LZ8I+DpjKlzbXj6yIqtEc=,iv:lw6NyhBNYmFIVgOHWJjaD0CvIQLdwQRJZQ7e3Zw/iX8=,tag:suIq5PncTk5z68C0sSYSfQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKS0xlZlA1b3VpcnBOM3Ez
            Sk4vbDFWdUc0MmQ3TnFiTWhxMmVqRy83MzI4Cng4N3RCajZGR1VMZjk5dHQvOXJK
            TVZsb1BHL04wQ2d3RnNaWHdDNWlZWVkKLS0tIGsxRkdMS3puMWFiQUwxTXZjT0sx
            YjYzck9RM2lpdGNua1RBSW1uZmJjb28KtYXS7fln7+wr+wf+HUV/oVFSHIHrjffS
            jsErcJsKU4Lz9kyE7h7sFqhn47fNMlBKjCCYBNz5UA4sAK++nKy8TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwm4xvd23tsx8m0h6xgxghkcxjzhucwm2djdfg0m88fwysjvdeys8gwn5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T10:40:13Z"
    mac: ENC[AES256_GCM,data:JJCX50fnbeCA6vbISlub2aeAPtCNwdI1MQbDU1edzsVVloGmcd8JhsFTaKAYLDBKOgZOjaskw+y6ZUNlwm4Hm6LDmDx0k6+dC2SHQp6kmdUKeF1PLRcUTF1TaLvPZyzE6+/G4Ksr5ASJ7p0+MwqxiZFIRWQH4qw9dsEZVhu9kSY=,iv:OnGr1lhBITwJ1P0sRLleA6g6eo2vVN5NZY2kFdoSfl0=,tag:Y/3sWtGOHIXlRQCzYygl1w==,type:str]
    version: 3.13.3
