apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:/ocY0Q==,iv:LclsNZGe1nxPKP8WUO96BMIw3UVtDG1xTZ71utDwovM=,tag:Q/WnCsarv76USJFOPYMWxg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:G2Z9Y7eyZhNtyY+Z5DXGMw==,iv:2yKRHP7cyQh+WDE/rbbydRl6HO0qNC1nJ5Hx6yuzGAE=,tag:xwQgyiR9mP/ZqF2zH911JQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcEtmU2sxQlVnVXZNQVMx
            ampCTTFuOUlqQ0lnaTlQRkNSS0x5K0VoNGdRCllCQlZXN2F4eTdqd05FcklQN3VU
            emdjZzFPU3BwRHFzaTJMamM2a3JkMUEKLS0tIGtIK01DZm5ZR2swRjFoKzV6dmQx
            cC9NWnIwS3ZWRUVZV09UeWpvZHBha2MK4k5ug7j+8tasJ4/KcyjCt2RUZGOudCy/
            8489vst8m8f6oI6zhgLLGVKZb7+srTuyMeUtNWISDwUGKs4+G73SzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwm4xvd23tsx8m0h6xgxghkcxjzhucwm2djdfg0m88fwysjvdeys8gwn5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T11:06:19Z"
    mac: ENC[AES256_GCM,data:oQFrcYKEE5hnwHII43BOYZEaYVVAxSbK99SlUKFcqcqbOIOgb7eSiRa/D5RcRRQs4OxQk4oB6/zZICwnodXye5eXecQUoHVHUr5nG8lRoUdI6hrBmVhO2KT0a8nOxgjBYdtT+d/IUxn2TxOUycwT9f8ocy488V2VUaLKddM18Kc=,iv:lq5TRvrrGsTuIRM5/pfW1xBSuNmohtaArqkZSLsTmW8=,tag:7in90TEiV1gg1I/8ZbFPIQ==,type:str]
    version: 3.13.3
