apiVersion: v1
data:
    password: ENC[AES256_GCM,data://lyTA==,iv:s7+/sAifQyqdSxrlqLQk49+CnKE7N4mS6pbAiCr/VOE=,tag:3T7J7OtXPWtfXDFsajn1MA==,type:str]
    user: ENC[AES256_GCM,data:qzMU94WaslI=,iv:OmM0F6dFAMorUzWZ4G5dt3HMRL6f5qNW1emqxoWt4bU=,tag:pJFK/n45t7MvK0HaQonohA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SCtJRUlhQlVicVoxMjBp
            ZVhUcm1uc2l3bUllZ1dicnpucW1KYWdlT1RFCmFRTldMK2tWSzFUREFJb1R0dm9H
            TVBXN1krMGowV2ZOb3A3NjlIbVRTSmMKLS0tIDY2M0dheXFCOTV2ekl2WTB4alFP
            OEQzR3F1V2JleHFIVnVBZnRIL3JkNFEK25X85dQICRx+Lt6PXlq8ESK2MIkAM3eY
            YzrRwU6E9AIdUiNSoLRdd73akASEFzyPAf9/c46zhJcUHHuENgbboQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwm4xvd23tsx8m0h6xgxghkcxjzhucwm2djdfg0m88fwysjvdeys8gwn5a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T14:47:58Z"
    mac: ENC[AES256_GCM,data:JZlp0zMNCJUPJKs1MFvpNnEXuB/uno5Aeh7ZbwBkrnurS8C+5ZT0p/DCyWUqpdKnCWvmqiIPHvnBl/1j4WQuzwmSftLTvO3kNnaWzCXsUQBgbmhEJwNR+sGKtfNj8EElM3pNPgzN9EIAq7zxEBfnNvi26lC2Qa1dr9p+ow+5TgI=,iv:T4e4gaNV+V9uPiM7pVaXfxkDHYmuE+AD80q+z7gXDyI=,tag:4JxONoMPZ6yJLyCoMjR4KQ==,type:str]
    version: 3.13.3
